tab4 <- read.table("household_power_consumption.txt", colClasses = c('character','character','numeric','numeric','numeric','numeric','numeric','numeric','numeric'), header=TRUE, sep=";", na.strings = "?")
tab4$Date <- as.Date(tab4$Date,"%d/%m/%Y")
tab4 <- subset(tab4,Date <= as.Date("2007/2/2") & Date >= as.Date("2007/2/1"))
tab4 <- tab4[complete.cases(tab4),]
dateTime <- setNames(paste(tab4$Date, tab4$Time),"DateTime")
tab4 <- cbind(dateTime, tab4[,!(names(tab4) %in% c("Date","Time"))])
tab4$dateTime <- as.POSIXct(dateTime)
par(mfrow=c(2,2), mar=c(4,4,2,1), oma=c(0,0,2,0))
with(tab4,
{
  plot(Global_active_power~dateTime, type="l", xlab="", ylab="Global Active Power (kW)")
  plot(Voltage~dateTime, type="l", xlab="", ylab="Volts (V)")
  plot(Sub_metering_1~dateTime, type="l", xlab="", ylab="Global Active Power (kW)")
  lines(Sub_metering_2~dateTime,col='Red')
  lines(Sub_metering_3~dateTime,col='Blue')
  legend("topright", col=c("black", "red", "blue"), lty=1, lwd=2, bty="n", legend=c("Sub_metering1", "Sub_metering2", "Sub_metering3"))
  plot(Global_reactive_power~dateTime, type="l", xlab="", ylab="Global Rective Power (kW)")
})
dev.copy(png, file="plot4.png", width=480, height=480)
dev.off()